set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

if(PORT STREQUAL "spdlog")
  set(VCPKG_CMAKE_CONFIGURE_OPTIONS -DSPDLOG_WCHAR_CONSOLE=ON -DSPDLOG_WCHAR_FILENAMES=ON)
endif()
