#pragma once

#include <windows.h>
#include <string>

class XEditLibCpp {
public:
    XEditLibCpp() {
        hModule = LoadLibrary(TEXT("XEditLib.dll"));
        if (hModule) {
            InitXEdit = (void(*)())GetProcAddress(hModule, "InitXEdit");
            CloseXEdit = (void(*)())GetProcAddress(hModule, "CloseXEdit");
            GetResultString = (bool(*)(wchar_t*, int))GetProcAddress(hModule, "GetResultString");
            GetResultArray = (bool(*)(unsigned int*, int))GetProcAddress(hModule, "GetResultArray");
            GetResultBytes = (bool(*)(unsigned char*, int))GetProcAddress(hModule, "GetResultBytes");
            GetGlobal = (bool(*)(wchar_t*, int*))GetProcAddress(hModule, "GetGlobal");
            GetGlobals = (bool(*)(int*))GetProcAddress(hModule, "GetGlobals");
            SetSortMode = (bool(*)(unsigned char, bool))GetProcAddress(hModule, "SetSortMode");
            Release = (bool(*)(unsigned int))GetProcAddress(hModule, "Release");
            ReleaseNodes = (bool(*)(unsigned int))GetProcAddress(hModule, "ReleaseNodes");
            Switch = (bool(*)(unsigned int, unsigned int))GetProcAddress(hModule, "Switch");
            GetDuplicateHandles = (bool(*)(unsigned int, int*))GetProcAddress(hModule, "GetDuplicateHandles");
            ResetStore = (bool(*)())GetProcAddress(hModule, "ResetStore");
            GetMessagesLength = (void(*)(int*))GetProcAddress(hModule, "GetMessagesLength");
            GetMessages = (bool(*)(wchar_t*, int))GetProcAddress(hModule, "GetMessages");
            ClearMessages = (void(*)())GetProcAddress(hModule, "ClearMessages");
            GetExceptionMessageLength = (void(*)(int*))GetProcAddress(hModule, "GetExceptionMessageLength");
            GetExceptionMessage = (bool(*)(wchar_t*, int))GetProcAddress(hModule, "GetExceptionMessage");
            GetGamePath = (bool(*)(int, int*))GetProcAddress(hModule, "GetGamePath");
            SetGamePath = (bool(*)(wchar_t*))GetProcAddress(hModule, "SetGamePath");
            GetGameLanguage = (bool(*)(int, int*))GetProcAddress(hModule, "GetGameLanguage");
            SetLanguage = (bool(*)(wchar_t*))GetProcAddress(hModule, "SetLanguage");
            SetBackupPath = (bool(*)(wchar_t*))GetProcAddress(hModule, "SetBackupPath");
            SetGameMode = (bool(*)(int))GetProcAddress(hModule, "SetGameMode");
            GetLoadOrder = (bool(*)(int*))GetProcAddress(hModule, "GetLoadOrder");
            GetActivePlugins = (bool(*)(int*))GetProcAddress(hModule, "GetActivePlugins");
            LoadPlugins = (bool(*)(wchar_t*, bool))GetProcAddress(hModule, "LoadPlugins");
            LoadPlugin = (bool(*)(wchar_t*))GetProcAddress(hModule, "LoadPlugin");
            LoadPluginHeader = (bool(*)(wchar_t*, unsigned int*))GetProcAddress(hModule, "LoadPluginHeader");
            BuildReferences = (bool(*)(unsigned int, bool))GetProcAddress(hModule, "BuildReferences");
            GetLoaderStatus = (bool(*)(unsigned char*))GetProcAddress(hModule, "GetLoaderStatus");
            UnloadPlugin = (bool(*)(unsigned int))GetProcAddress(hModule, "UnloadPlugin");
            AddFile = (bool(*)(wchar_t*, unsigned int*))GetProcAddress(hModule, "AddFile");
            FileByIndex = (bool(*)(int, unsigned int*))GetProcAddress(hModule, "FileByIndex");
            FileByLoadOrder = (bool(*)(int, unsigned int*))GetProcAddress(hModule, "FileByLoadOrder");
            FileByName = (bool(*)(wchar_t*, unsigned int*))GetProcAddress(hModule, "FileByName");
            FileByAuthor = (bool(*)(wchar_t*, unsigned int*))GetProcAddress(hModule, "FileByAuthor");
            SaveFile = (bool(*)(unsigned int, wchar_t*))GetProcAddress(hModule, "SaveFile");
            GetRecordCount = (bool(*)(unsigned int, int*))GetProcAddress(hModule, "GetRecordCount");
            GetOverrideRecordCount = (bool(*)(unsigned int, int*))GetProcAddress(hModule, "GetOverrideRecordCount");
            MD5Hash = (bool(*)(unsigned int, int*))GetProcAddress(hModule, "MD5Hash");
            CRCHash = (bool(*)(unsigned int, int*))GetProcAddress(hModule, "CRCHash");
            SortEditorIDs = (bool(*)(unsigned int, wchar_t*))GetProcAddress(hModule, "SortEditorIDs");
            SortNames = (bool(*)(unsigned int, wchar_t*))GetProcAddress(hModule, "SortNames");
            GetFileLoadOrder = (bool(*)(unsigned int, int*))GetProcAddress(hModule, "GetFileLoadOrder");
            ExtractContainer = (bool(*)(wchar_t*, wchar_t*, bool))GetProcAddress(hModule, "ExtractContainer");
            ExtractFile = (bool(*)(wchar_t*, wchar_t*, wchar_t*))GetProcAddress(hModule, "ExtractFile");
            GetContainerFiles = (bool(*)(wchar_t*, wchar_t*, int*))GetProcAddress(hModule, "GetContainerFiles");
            GetFileContainer = (bool(*)(wchar_t*, int*))GetProcAddress(hModule, "GetFileContainer");
            GetLoadedContainers = (bool(*)(int*))GetProcAddress(hModule, "GetLoadedContainers");
            LoadContainer = (bool(*)(wchar_t*))GetProcAddress(hModule, "LoadContainer");
            BuildArchive = (bool(*)(wchar_t*, wchar_t*, wchar_t*, int, bool, bool, wchar_t*, wchar_t*))GetProcAddress(hModule, "BuildArchive");
            GetTextureData = (bool(*)(wchar_t*, int*, int*))GetProcAddress(hModule, "GetTextureData");
            CleanMasters = (bool(*)(unsigned int))GetProcAddress(hModule, "CleanMasters");
            SortMasters = (bool(*)(unsigned int))GetProcAddress(hModule, "SortMasters");
            AddMaster = (bool(*)(unsigned int, wchar_t*))GetProcAddress(hModule, "AddMaster");
            AddMasters = (bool(*)(unsigned int, wchar_t*))GetProcAddress(hModule, "AddMasters");
            AddRequiredMasters = (bool(*)(unsigned int, unsigned int, bool))GetProcAddress(hModule, "AddRequiredMasters");
            GetMasters = (bool(*)(unsigned int, int*))GetProcAddress(hModule, "GetMasters");
            GetRequiredBy = (bool(*)(unsigned int, int*))GetProcAddress(hModule, "GetRequiredBy");
            GetMasterNames = (bool(*)(unsigned int, int*))GetProcAddress(hModule, "GetMasterNames");
            HasElement = (bool(*)(unsigned int, wchar_t*, bool*))GetProcAddress(hModule, "HasElement");
            GetElement = (bool(*)(unsigned int, wchar_t*, unsigned int*))GetProcAddress(hModule, "GetElement");
            AddElement = (bool(*)(unsigned int, wchar_t*, unsigned int*))GetProcAddress(hModule, "AddElement");
            AddElementValue = (bool(*)(unsigned int, wchar_t*, wchar_t*, unsigned int*))GetProcAddress(hModule, "AddElementValue");
            RemoveElement = (bool(*)(unsigned int, wchar_t*))GetProcAddress(hModule, "RemoveElement");
            RemoveElementOrParent = (bool(*)(unsigned int))GetProcAddress(hModule, "RemoveElementOrParent");
            SetElement = (bool(*)(unsigned int, unsigned int))GetProcAddress(hModule, "SetElement");
            GetElements = (bool(*)(unsigned int, wchar_t*, bool, bool, int*))GetProcAddress(hModule, "GetElements");
            GetDefNames = (bool(*)(unsigned int, int*))GetProcAddress(hModule, "GetDefNames");
            GetAddList = (bool(*)(unsigned int, int*))GetProcAddress(hModule, "GetAddList");
            GetLinksTo = (bool(*)(unsigned int, wchar_t*, unsigned int*))GetProcAddress(hModule, "GetLinksTo");
            SetLinksTo = (bool(*)(unsigned int, wchar_t*, unsigned int))GetProcAddress(hModule, "SetLinksTo");
            GetElementIndex = (bool(*)(unsigned int, int*))GetProcAddress(hModule, "GetElementIndex");
            GetContainer = (bool(*)(unsigned int, unsigned int*))GetProcAddress(hModule, "GetContainer");
            GetElementFile = (bool(*)(unsigned int, unsigned int*))GetProcAddress(hModule, "GetElementFile");
            GetElementRecord = (bool(*)(unsigned int, unsigned int*))GetProcAddress(hModule, "GetElementRecord");
            ElementCount = (bool(*)(unsigned int, int*))GetProcAddress(hModule, "ElementCount");
            ElementEquals = (bool(*)(unsigned int, unsigned int, bool*))GetProcAddress(hModule, "ElementEquals");
            ElementMatches = (bool(*)(unsigned int, wchar_t*, wchar_t*, bool*))GetProcAddress(hModule, "ElementMatches");
            HasArrayItem = (bool(*)(unsigned int, wchar_t*, wchar_t*, wchar_t*, bool*))GetProcAddress(hModule, "HasArrayItem");
            GetArrayItem = (bool(*)(unsigned int, wchar_t*, wchar_t*, wchar_t*, unsigned int*))GetProcAddress(hModule, "GetArrayItem");
            AddArrayItem = (bool(*)(unsigned int, wchar_t*, wchar_t*, wchar_t*, unsigned int*))GetProcAddress(hModule, "AddArrayItem");
            RemoveArrayItem = (bool(*)(unsigned int, wchar_t*, wchar_t*, wchar_t*))GetProcAddress(hModule, "RemoveArrayItem");
            MoveArrayItem = (bool(*)(unsigned int, int))GetProcAddress(hModule, "MoveArrayItem");
            CopyElement = (bool(*)(unsigned int, unsigned int, bool, unsigned int*))GetProcAddress(hModule, "CopyElement");
            GetSignatureAllowed = (bool(*)(unsigned int, wchar_t*, bool*))GetProcAddress(hModule, "GetSignatureAllowed");
            GetAllowedSignatures = (bool(*)(unsigned int, int*))GetProcAddress(hModule, "GetAllowedSignatures");
            GetIsModified = (bool(*)(unsigned int, bool*))GetProcAddress(hModule, "GetIsModified");
            GetIsEditable = (bool(*)(unsigned int, bool*))GetProcAddress(hModule, "GetIsEditable");
            GetIsRemoveable = (bool(*)(unsigned int, bool*))GetProcAddress(hModule, "GetIsRemoveable");
            GetCanAdd = (bool(*)(unsigned int, bool*))GetProcAddress(hModule, "GetCanAdd");
            SortKey = (bool(*)(unsigned int, int*))GetProcAddress(hModule, "SortKey");
            ElementType = (bool(*)(unsigned int, unsigned char*))GetProcAddress(hModule, "ElementType");
            DefType = (bool(*)(unsigned int, unsigned char*))GetProcAddress(hModule, "DefType");
            SmashType = (bool(*)(unsigned int, unsigned char*))GetProcAddress(hModule, "SmashType");
            ValueType = (bool(*)(unsigned int, unsigned char*))GetProcAddress(hModule, "ValueType");
            IsSorted = (bool(*)(unsigned int, bool*))GetProcAddress(hModule, "IsSorted");
            Name = (bool(*)(unsigned int, int*))GetProcAddress(hModule, "Name");
            LongName = (bool(*)(unsigned int, int*))GetProcAddress(hModule, "LongName");
            DisplayName = (bool(*)(unsigned int, int*))GetProcAddress(hModule, "DisplayName");
            Path = (bool(*)(unsigned int, bool, bool, int*))GetProcAddress(hModule, "Path");
            Signature = (bool(*)(unsigned int, int*))GetProcAddress(hModule, "Signature");
            GetValue = (bool(*)(unsigned int, wchar_t*, int*))GetProcAddress(hModule, "GetValue");
            SetValue = (bool(*)(unsigned int, wchar_t*, wchar_t*))GetProcAddress(hModule, "SetValue");
            GetIntValue = (bool(*)(unsigned int, wchar_t*, int*))GetProcAddress(hModule, "GetIntValue");
            SetIntValue = (bool(*)(unsigned int, wchar_t*, int))GetProcAddress(hModule, "SetIntValue");
            GetUIntValue = (bool(*)(unsigned int, wchar_t*, unsigned int*))GetProcAddress(hModule, "GetUIntValue");
            SetUIntValue = (bool(*)(unsigned int, wchar_t*, unsigned int))GetProcAddress(hModule, "SetUIntValue");
            GetFloatValue = (bool(*)(unsigned int, wchar_t*, double*))GetProcAddress(hModule, "GetFloatValue");
            SetFloatValue = (bool(*)(unsigned int, wchar_t*, double))GetProcAddress(hModule, "SetFloatValue");
            GetFlag = (bool(*)(unsigned int, wchar_t*, wchar_t*, bool*))GetProcAddress(hModule, "GetFlag");
            SetFlag = (bool(*)(unsigned int, wchar_t*, wchar_t*, bool))GetProcAddress(hModule, "SetFlag");
            GetAllFlags = (bool(*)(unsigned int, wchar_t*, int*))GetProcAddress(hModule, "GetAllFlags");
            GetEnabledFlags = (bool(*)(unsigned int, wchar_t*, int*))GetProcAddress(hModule, "GetEnabledFlags");
            SetEnabledFlags = (bool(*)(unsigned int, wchar_t*, wchar_t*))GetProcAddress(hModule, "SetEnabledFlags");
            GetEnumOptions = (bool(*)(unsigned int, wchar_t*, int*))GetProcAddress(hModule, "GetEnumOptions");
            SignatureFromName = (bool(*)(wchar_t*, int*))GetProcAddress(hModule, "SignatureFromName");
            NameFromSignature = (bool(*)(wchar_t*, int*))GetProcAddress(hModule, "NameFromSignature");
            GetSignatureNameMap = (bool(*)(int*))GetProcAddress(hModule, "GetSignatureNameMap");
            ElementToJson = (bool(*)(unsigned int, int*))GetProcAddress(hModule, "ElementToJson");
            ElementFromJson = (bool(*)(unsigned int, wchar_t*, wchar_t*))GetProcAddress(hModule, "ElementFromJson");
            GetFormID = (bool(*)(unsigned int, unsigned int*, bool))GetProcAddress(hModule, "GetFormID");
            SetFormID = (bool(*)(unsigned int, unsigned int, bool, bool))GetProcAddress(hModule, "SetFormID");
            GetRecord = (bool(*)(unsigned int, unsigned int, bool, unsigned int*))GetProcAddress(hModule, "GetRecord");
            GetRecords = (bool(*)(unsigned int, wchar_t*, bool, int*))GetProcAddress(hModule, "GetRecords");
            GetREFRs = (bool(*)(unsigned int, wchar_t*, unsigned int, int*))GetProcAddress(hModule, "GetREFRs");
            GetOverrides = (bool(*)(unsigned int, int*))GetProcAddress(hModule, "GetOverrides");
            GetMasterRecord = (bool(*)(unsigned int, unsigned int*))GetProcAddress(hModule, "GetMasterRecord");
            GetWinningOverride = (bool(*)(unsigned int, unsigned int*))GetProcAddress(hModule, "GetWinningOverride");
            GetInjectionTarget = (bool(*)(unsigned int, unsigned int*))GetProcAddress(hModule, "GetInjectionTarget");
            FindNextRecord = (bool(*)(unsigned int, wchar_t*, bool, bool, unsigned int*))GetProcAddress(hModule, "FindNextRecord");
            FindPreviousRecord = (bool(*)(unsigned int, wchar_t*, bool, bool, unsigned int*))GetProcAddress(hModule, "FindPreviousRecord");
            FindValidReferences = (bool(*)(unsigned int, wchar_t*, wchar_t*, int, int*))GetProcAddress(hModule, "FindValidReferences");
            GetReferencedBy = (bool(*)(unsigned int, int*))GetProcAddress(hModule, "GetReferencedBy");
            ExchangeReferences = (bool(*)(unsigned int, unsigned int, unsigned int))GetProcAddress(hModule, "ExchangeReferences");
            IsMaster = (bool(*)(unsigned int, bool*))GetProcAddress(hModule, "IsMaster");
            IsInjected = (bool(*)(unsigned int, bool*))GetProcAddress(hModule, "IsInjected");
            IsOverride = (bool(*)(unsigned int, bool*))GetProcAddress(hModule, "IsOverride");
            IsWinningOverride = (bool(*)(unsigned int, bool*))GetProcAddress(hModule, "IsWinningOverride");
            GetNodes = (bool(*)(unsigned int, unsigned int*))GetProcAddress(hModule, "GetNodes");
            GetConflictData = (bool(*)(unsigned int, unsigned int, unsigned char*, unsigned char*))GetProcAddress(hModule, "GetConflictData");
            GetNodeElements = (bool(*)(unsigned int, unsigned int, int*))GetProcAddress(hModule, "GetNodeElements");
            CheckForErrors = (bool(*)(unsigned int))GetProcAddress(hModule, "CheckForErrors");
            GetErrorThreadDone = (bool(*)())GetProcAddress(hModule, "GetErrorThreadDone");
            GetErrors = (bool(*)(int*))GetProcAddress(hModule, "GetErrors");
            GetErrorString = (bool(*)(unsigned int, int*))GetProcAddress(hModule, "GetErrorString");
            RemoveIdenticalRecords = (bool(*)(unsigned int, bool, bool))GetProcAddress(hModule, "RemoveIdenticalRecords");
            FilterRecord = (bool(*)(unsigned int))GetProcAddress(hModule, "FilterRecord");
            ResetFilter = (bool(*)())GetProcAddress(hModule, "ResetFilter");
        }
    }

    ~XEditLibCpp() {
        if (hModule) {
            FreeLibrary(hModule);
        }
    }

    // Declare function pointers
    void (*InitXEdit)();
    void (*CloseXEdit)();
    bool (*GetResultString)(wchar_t* str, int len);
    bool (*GetResultArray)(unsigned int* res, int len);
    bool (*GetResultBytes)(unsigned char* res, int len);
    bool (*GetGlobal)(wchar_t* key, int* len);
    bool (*GetGlobals)(int* len);
    bool (*SetSortMode)(unsigned char sortBy, bool reverse);
    bool (*Release)(unsigned int id);
    bool (*ReleaseNodes)(unsigned int id);
    bool (*Switch)(unsigned int id, unsigned int id2);
    bool (*GetDuplicateHandles)(unsigned int id, int* len);
    bool (*ResetStore)();
    void (*GetMessagesLength)(int* len);
    bool (*GetMessages)(wchar_t* str, int len);
    void (*ClearMessages)();
    void (*GetExceptionMessageLength)(int* len);
    bool (*GetExceptionMessage)(wchar_t* str, int len);
    bool (*GetGamePath)(int mode, int* len);
    bool (*SetGamePath)(wchar_t* path);
    bool (*GetGameLanguage)(int mode, int* len);
    bool (*SetLanguage)(wchar_t* lang);
    bool (*SetBackupPath)(wchar_t* path);
    bool (*SetGameMode)(int mode);
    bool (*GetLoadOrder)(int* len);
    bool (*GetActivePlugins)(int* len);
    bool (*LoadPlugins)(wchar_t* loadOrder, bool smartLoad);
    bool (*LoadPlugin)(wchar_t* filename);
    bool (*LoadPluginHeader)(wchar_t* fileName, unsigned int* res);
    bool (*BuildReferences)(unsigned int id, bool synchronous);
    bool (*GetLoaderStatus)(unsigned char* status);
    bool (*UnloadPlugin)(unsigned int id);
    bool (*AddFile)(wchar_t* filename, unsigned int* res);
    bool (*FileByIndex)(int index, unsigned int* res);
    bool (*FileByLoadOrder)(int load_order, unsigned int* res);
    bool (*FileByName)(wchar_t* name, unsigned int* res);
    bool (*FileByAuthor)(wchar_t* author, unsigned int* res);
    bool (*SaveFile)(unsigned int id, wchar_t* filePath);
    bool (*GetRecordCount)(unsigned int id, int* count);
    bool (*GetOverrideRecordCount)(unsigned int id, int* count);
    bool (*MD5Hash)(unsigned int id, int* len);
    bool (*CRCHash)(unsigned int id, int* len);
    bool (*SortEditorIDs)(unsigned int id, wchar_t* sig);
    bool (*SortNames)(unsigned int id, wchar_t* sig);
    bool (*GetFileLoadOrder)(unsigned int id, int* loadOrder);
    bool (*ExtractContainer)(wchar_t* name, wchar_t* destination, bool replace);
    bool (*ExtractFile)(wchar_t* name, wchar_t* source, wchar_t* destination);
    bool (*GetContainerFiles)(wchar_t* name, wchar_t* path, int* len);
    bool (*GetFileContainer)(wchar_t* path, int* len);
    bool (*GetLoadedContainers)(int* len);
    bool (*LoadContainer)(wchar_t* filePath);
    bool (*BuildArchive)(wchar_t* name, wchar_t* folder, wchar_t* filePaths, int archiveType, bool bCompress, bool bShare, wchar_t* af, wchar_t* ff);
    bool (*GetTextureData)(wchar_t* resourceName, int* width, int* height);
    bool (*CleanMasters)(unsigned int id);
    bool (*SortMasters)(unsigned int id);
    bool (*AddMaster)(unsigned int id, wchar_t* masterName);
    bool (*AddMasters)(unsigned int id, wchar_t* masters);
    bool (*AddRequiredMasters)(unsigned int id, unsigned int id2, bool asNew);
    bool (*GetMasters)(unsigned int id, int* len);
    bool (*GetRequiredBy)(unsigned int id, int* len);
    bool (*GetMasterNames)(unsigned int id, int* len);
    bool (*HasElement)(unsigned int id, wchar_t* key, bool* bool_val);
    bool (*GetElement)(unsigned int id, wchar_t* key, unsigned int* res);
    bool (*AddElement)(unsigned int id, wchar_t* key, unsigned int* res);
    bool (*AddElementValue)(unsigned int id, wchar_t* key, wchar_t* value, unsigned int* res);
    bool (*RemoveElement)(unsigned int id, wchar_t* key);
    bool (*RemoveElementOrParent)(unsigned int id);
    bool (*SetElement)(unsigned int id, unsigned int id2);
    bool (*GetElements)(unsigned int id, wchar_t* key, bool sort, bool filter, int* len);
    bool (*GetDefNames)(unsigned int id, int* len);
    bool (*GetAddList)(unsigned int id, int* len);
    bool (*GetLinksTo)(unsigned int id, wchar_t* key, unsigned int* res);
    bool (*SetLinksTo)(unsigned int id, wchar_t* key, unsigned int id2);
    bool (*GetElementIndex)(unsigned int id, int* index);
    bool (*GetContainer)(unsigned int id, unsigned int* res);
    bool (*GetElementFile)(unsigned int id, unsigned int* res);
    bool (*GetElementRecord)(unsigned int id, unsigned int* res);
    bool (*ElementCount)(unsigned int id, int* count);
    bool (*ElementEquals)(unsigned int id, unsigned int id2, bool* bool_val);
    bool (*ElementMatches)(unsigned int id, wchar_t* path, wchar_t* value, bool* bool_val);
    bool (*HasArrayItem)(unsigned int id, wchar_t* path, wchar_t* subpath, wchar_t* value, bool* bool_val);
    bool (*GetArrayItem)(unsigned int id, wchar_t* path, wchar_t* subpath, wchar_t* value, unsigned int* res);
    bool (*AddArrayItem)(unsigned int id, wchar_t* path, wchar_t* subpath, wchar_t* value, unsigned int* res);
    bool (*RemoveArrayItem)(unsigned int id, wchar_t* path, wchar_t* subpath, wchar_t* value);
    bool (*MoveArrayItem)(unsigned int id, int index);
    bool (*CopyElement)(unsigned int id, unsigned int id2, bool aAsNew, unsigned int* res);
    bool (*GetSignatureAllowed)(unsigned int id, wchar_t* sig, bool* bool_val);
    bool (*GetAllowedSignatures)(unsigned int id, int* len);
    bool (*GetIsModified)(unsigned int id, bool* bool_val);
    bool (*GetIsEditable)(unsigned int id, bool* bool_val);
    bool (*GetIsRemoveable)(unsigned int id, bool* bool_val);
    bool (*GetCanAdd)(unsigned int id, bool* bool_val);
    bool (*SortKey)(unsigned int id, int* len);
    bool (*ElementType)(unsigned int id, unsigned char* enumVal);
    bool (*DefType)(unsigned int id, unsigned char* enumVal);
    bool (*SmashType)(unsigned int id, unsigned char* enumVal);
    bool (*ValueType)(unsigned int id, unsigned char* enumVal);
    bool (*IsSorted)(unsigned int id, bool* bool_val);
    bool (*Name)(unsigned int id, int* len);
    bool (*LongName)(unsigned int id, int* len);
    bool (*DisplayName)(unsigned int id, int* len);
    bool (*Path)(unsigned int id, bool shortPath, bool local, int* len);
    bool (*Signature)(unsigned int id, int* len);
    bool (*GetValue)(unsigned int id, wchar_t* path, int* len);
    bool (*SetValue)(unsigned int id, wchar_t* path, wchar_t* value);
    bool (*GetIntValue)(unsigned int id, wchar_t* path, int* value);
    bool (*SetIntValue)(unsigned int id, wchar_t* path, int value);
    bool (*GetUIntValue)(unsigned int id, wchar_t* path, unsigned int* value);
    bool (*SetUIntValue)(unsigned int id, wchar_t* path, unsigned int value);
    bool (*GetFloatValue)(unsigned int id, wchar_t* path, double* value);
    bool (*SetFloatValue)(unsigned int id, wchar_t* path, double value);
    bool (*GetFlag)(unsigned int id, wchar_t* path, wchar_t* name, bool* enabled);
    bool (*SetFlag)(unsigned int id, wchar_t* path, wchar_t* name, bool enabled);
    bool (*GetAllFlags)(unsigned int id, wchar_t* path, int* len);
    bool (*GetEnabledFlags)(unsigned int id, wchar_t* path, int* len);
    bool (*SetEnabledFlags)(unsigned int id, wchar_t* path, wchar_t* flags);
    bool (*GetEnumOptions)(unsigned int id, wchar_t* path, int* len);
    bool (*SignatureFromName)(wchar_t* name, int* len);
    bool (*NameFromSignature)(wchar_t* sig, int* len);
    bool (*GetSignatureNameMap)(int* len);
    bool (*ElementToJson)(unsigned int id, int* len);
    bool (*ElementFromJson)(unsigned int id, wchar_t* path, wchar_t* json);
    bool (*GetFormID)(unsigned int id, unsigned int* formID, bool local);
    bool (*SetFormID)(unsigned int id, unsigned int formID, bool local, bool fixReferences);
    bool (*GetRecord)(unsigned int id, unsigned int formID, bool searchMasters, unsigned int* res);
    bool (*GetRecords)(unsigned int id, wchar_t* search, bool includeOverrides, int* len);
    bool (*GetREFRs)(unsigned int id, wchar_t* search, unsigned int flags, int* len);
    bool (*GetOverrides)(unsigned int id, int* count);
    bool (*GetMasterRecord)(unsigned int id, unsigned int* res);
    bool (*GetWinningOverride)(unsigned int id, unsigned int* res);
    bool (*GetInjectionTarget)(unsigned int id, unsigned int* res);
    bool (*FindNextRecord)(unsigned int id, wchar_t* search, bool byEdid, bool byName, unsigned int* res);
    bool (*FindPreviousRecord)(unsigned int id, wchar_t* search, bool byEdid, bool byName, unsigned int* res);
    bool (*FindValidReferences)(unsigned int id, wchar_t* signature, wchar_t* search, int limitTo, int* len);
    bool (*GetReferencedBy)(unsigned int id, int* len);
    bool (*ExchangeReferences)(unsigned int id, unsigned int oldFormID, unsigned int newFormID);
    bool (*IsMaster)(unsigned int id, bool* bool_val);
    bool (*IsInjected)(unsigned int id, bool* bool_val);
    bool (*IsOverride)(unsigned int id, bool* bool_val);
    bool (*IsWinningOverride)(unsigned int id, bool* bool_val);
    bool (*GetNodes)(unsigned int id, unsigned int* res);
    bool (*GetConflictData)(unsigned int id, unsigned int id2, unsigned char* conflictAll, unsigned char* conflictThis);
    bool (*GetNodeElements)(unsigned int id, unsigned int id2, int* len);
    bool (*CheckForErrors)(unsigned int id);
    bool (*GetErrorThreadDone)();
    bool (*GetErrors)(int* len);
    bool (*GetErrorString)(unsigned int id, int* len);
    bool (*RemoveIdenticalRecords)(unsigned int id, bool removeITMs, bool removeITPOs);
    bool (*FilterRecord)(unsigned int id);
    bool (*ResetFilter)();

    // Helpers
    std::wstring getResultStringSafe(int len) {
        wchar_t* str = new wchar_t[len];
        GetResultString(str, len);

        std::wstring out_str(str);
        out_str.erase(len);

        return out_str;
    }

    wchar_t* WStringToWChar(std::wstring str) {
        wchar_t* wcharArray = new wchar_t[str.size() + 1];
        wcscpy_s(wcharArray, str.size() + 1, str.c_str());
        return wcharArray;
    }

private:
    HMODULE hModule;
};
